##⇓ (osc.lua)
script-opts-add = osc-layout=floating
script-opts-add = osc-seekbarstyle=knob
script-opts-add = osc-timetotal=yes
script-opts-add = osc-windowcontrols=no
script-opts-add = osc-visibility_modes=auto_always
script-opts-add = osc-menu_mbtn_left_command=show-text ${playlist} 3000
script-opts-add = osc-title_mbtn_right_command=set clipboard/text ${path}
script-opts-add = osc-sub_track_mbtn_right_command=cycle secondary-sid
script-opts-add = osc-audio_track_mbtn_right_command=cycle audio down
script-opts-add = osc-volume_mbtn_right_command=no-osd cycle mute
script-opts-add = osc-audio_track_mbtn_mid_command=

##⇓ (console.lua)
script-opts-add = console-scale_with_window=no

##⇓ (ytdl.lua)
script-opts-add = ytdl_hook-all_formats=yes
